services:
    api:
        platform: ${PISTON_PLATFORM:-linux/amd64}
        build:
            context: .
            dockerfile: ${PISTON_DOCKERFILE:-Dockerfile.x86}
        container_name: piston_api
        restart: always
        privileged: true
        env_file: .env
        ports:
            - "${PORT:-2000}:2000"
        volumes:
            - ./data/piston/packages:/piston/packages
            - ./data/piston/data:/piston/data
        tmpfs:
            - /tmp:exec
